
services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    command: bash -c "python manage.py collectstatic && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app 

  frontend:
    build: ./front-end/chatbotfuria
    ports:
      - "3000:3000"
    command: npm run dev 
    volumes:
      - ./front-end/chatbotfuria:/app
      - /app/node_modules