# Generated by Django 5.2 on 2025-04-30 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=12)),
                ('buy', models.CharField(max_length=10)),
                ('buy_details', models.CharField(blank=True, max_length=255, null=True)),
                ('attended_event', models.CharField(max_length=10)),
                ('event_count', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_conversation_history', models.BooleanField(default=False)),
                ('accept_lgpd', models.BooleanField(default=False)),
                ('twitter_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('reddit_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
