# Generated by Django 5.2 on 2025-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizentry',
            name='attended_event',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='buy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
