# Generated by Django 5.2 on 2025-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quizentry_attended_event_alter_quizentry_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizentry',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='rg',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
