# Generated by Django 5.2 on 2025-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizentry_cpf_alter_quizentry_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizentry',
            name='reddit_handle',
        ),
        migrations.RemoveField(
            model_name='quizentry',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='quizentry',
            name='social_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quizentry',
            name='validation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizentry',
            name='validation_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='accept_lgpd',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='attended_event',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='buy',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='buy_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='cpf',
            field=models.CharField(default=2, max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='event_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='rg',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
