# Generated by Django 5.2 on 2025-05-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_twitterlinkedaccount_delete_socialtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizentry',
            name='fan_level',
            field=models.CharField(blank=True, choices=[('not_fan', 'Não é torcedor'), ('casual_fan', 'Torcedor Casual'), ('regular_fan', 'Torcedor Regular'), ('hardcore_fan', 'Torcedor Fanático')], max_length=50),
        ),
        migrations.AddField(
            model_name='quizentry',
            name='fan_score',
            field=models.IntegerField(default=0),
        ),
    ]
