# Generated by Django 5.2 on 2025-05-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quizentry_fan_level_quizentry_fan_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizentry',
            name='buy_details',
            field=models.IntegerField(default=0),
        ),
    ]
