# Generated by Django 5.2 on 2025-05-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizentry_buy_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizentry',
            name='social_links',
        ),
    ]
