# Generated by Django 5.2 on 2025-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_remove_quizentry_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizentry',
            name='buy_details',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
