# Generated by Django 5.2 on 2025-05-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_quizentry_buy_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizentry',
            name='validation_details',
        ),
        migrations.RemoveField(
            model_name='quizentry',
            name='validation_result',
        ),
        migrations.AlterField(
            model_name='quizentry',
            name='fan_level',
            field=models.CharField(blank=True, choices=[('not_fan', 'Não é torcedor'), ('regular_fan', 'Torcedor Regular'), ('big_fan', 'Grande fã'), ('fanatico', 'Fanático'), ('doido_por_furia', 'Doido por FURIA!!')], max_length=50),
        ),
    ]
