# Generated by Django 5.2 on 2025-05-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_fancard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fancard',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fan_photos/'),
        ),
    ]
