# Generated by Django 5.2 on 2025-05-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_fancard_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizentry',
            name='fan_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição personalizada do fã'),
        ),
    ]
